version: "3.9"

services:
  caddy:
    image: caddy:alpine
    container_name: recipe_caddy
    ports:
      - "8080:80"
    volumes:
      - ./app:/srv/app:ro
      - ./images:/srv/images:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped
